### ISSUE TITLE
Attempt to increment/decrement property "total_fixed_exceptions" on null

### ISSUE THREAD

**Issue by balthild** [LaraBug/larabug-app#109]
The exception is thrown at
https://github.com/LaraBug/larabug-app/blob/8ba75768ca80ab7d14c98878691cffaaef14f0c1/app/Models/Statistic.php#L22

I checked the database and find that there's no record in the `statistics` table.

The record should have been created at this event listerner
https://github.com/LaraBug/larabug-app/blob/8ba75768ca80ab7d14c98878691cffaaef14f0c1/app/Listeners/UpdateStatistics.php#L19-L21

But the event listener are commented out at
https://github.com/LaraBug/larabug-app/blob/8ba75768ca80ab7d14c98878691cffaaef14f0c1/app/Providers/EventServiceProvider.php#L26

Is it done by accident?

**Comment by Cannonb4ll** [comment]
It's old code which is not used anymore, feel free to submit a PR to fix this.
