### ISSUE TITLE
No request body for custom webhooks

### ISSUE THREAD

**Issue by lpheller** [LaraBug/larabug-app#114]
I'm having problems setting up a custom notification webhook. 

When using the custom webhook, the endpoint is called but it doesn't receive this data defined for the WebhookMessage class:
https://github.com/LaraBug/larabug-app/blob/f608eab3a36c1c9679c1feb9683ca0afe01dce05/app/Notifications/ExceptionWasCreated.php#L144-L153
The request body is just empty. 

Also, while the custom user-agent is applied, the request is missing a "Content-Type" header, but tries to send json encoded content.

https://github.com/LaraBug/larabug-app/blob/f608eab3a36c1c9679c1feb9683ca0afe01dce05/app/Notifications/CustomWebhook/WebhookChannel.php#L43

When adding the `Content-Type: application/json` header, the webhook request contains the required information. 

Is there something I'm missing, forgetting or doing wrong in my setup?  Because I don't understand how the current configuration with an empty "Content-Type" header and an empty request body could ever have worked.

**Comment by Cannonb4ll** [comment]
Can you verify your PR solved the issue?

**Comment by lpheller** [comment]
Hmm, sadly It still doesn't seem to work within my account on larabug.com. However in my local copy of the larabug app everything works as expected with exactly the same webhook url as used in the larabug.com project.
Now I am a bit at a loss...

**Comment by lpheller** [comment]
Oh, the content-type header of the request coming from larabug.com is still empty. Perhaps the update has not reached the notification system yet?

**Comment by Cannonb4ll** [comment]
Should be live now, we did a deployment last week. Can you verify?

**Comment by lpheller** [comment]
Yes, I can confirm, the Webhook request now contains the required data.
Thanks 👍🏻

**Comment by Cannonb4ll** [comment]
Beautifully!
