### ISSUE TITLE
Option to change your password from panel

### ISSUE THREAD

**Issue by SebastiaanKloos** [LaraBug/larabug-app#15]
Currenly, there is no option to change your password from the panel. Let's change that!

**Comment by SebastiaanKloos** [comment]
Fixed with PR #16

**Comment by Glennmen** [comment]
@SebastiaanKloos btw if you add `Fixes #15` in your PR description it will auto close this issue once it gets merged 😉
Github tricks https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by SebastiaanKloos** [comment]
@Glennmen TIL - Thanks! Didn't know it works when cross-referencing pull-requests / issues
