### ISSUE TITLE
[Request]: Group exceptions into a single exception item

### ISSUE THREAD

**Issue by abishekrsrikaanth** [LaraBug/larabug-app#31]
Can you add this feature to group exceptions into a single exception item instead of showing the same exception multiple times? This will also help identify total occurrences in the past and traverse between each occurrence. Possibly a line chart can be added to see how frequently these exceptions occur.

**Comment by SebastiaanKloos** [comment]
@abishekrsrikaanth I'm working on an issues feature which groups the exceptions. I think a graph wouldn't work as exceptions are purged after an amount of time. We'll think about how we would implement such a feature. For now I'll close this issue as we are working on the issues feature :)
