### ISSUE TITLE
[Idea] Browser notifications

### ISSUE THREAD

**Issue by ricklambrechts** [LaraBug/larabug-app#50]
Do we want to use browser notifications?
With the already used package "laravel-notification-channels/fcm".

**Comment by Cannonb4ll** [comment]
We can do that, not sure if you can do that with FCM. FCM package has been included to have mobile app push notifications (which already work for iOS :))

**Comment by Cannonb4ll** [comment]
For now, we're not going to work on this. Obviously, we do accept a PR implementing this feature. More than welcome!
