### ISSUE TITLE
How to logout from LaraBug after logging in?

### ISSUE THREAD

**Issue by NabilHassen** [LaraBug/larabug-app#63]

**Comment by Glennmen** [comment]
Scroll down in Profile:
![CleanShot 2021-11-15 at 20 49 47](https://user-images.githubusercontent.com/11406433/141844963-5d99d99d-3838-47f5-9e3c-ae7a28ec81ee.png)


This could indeed be placed in a better location.

**Comment by Cannonb4ll** [comment]
@Glennmen Please submit a PR with a fix for this 🥰

**Comment by Glennmen** [comment]
@Cannonb4ll Sure! Let me see what I can do.

**Comment by Cannonb4ll** [comment]
Added this issue to the roadmap. Looking forward to your contribution @Glennmen <3

**Comment by Glennmen** [comment]
@Cannonb4ll I hope to start on it soon 😄 I haven't forgotten about it.
