### ISSUE TITLE
Resend Email Verification Error

### ISSUE THREAD

**Issue by stephenjude** [LaraBug/larabug-app#77]
<img width="1111" alt="Screenshot 2022-04-04 at 8 24 39 PM" src="https://user-images.githubusercontent.com/31182887/161619884-0ddb0ab7-e264-46ab-9aec-39a8646544a3.png">

<img width="1111" alt="Screenshot 2022-04-04 at 8 24 33 PM" src="https://user-images.githubusercontent.com/31182887/161619941-43e57816-19d2-41c7-a252-c2b07d1f9f5f.png">

**Comment by Cannonb4ll** [comment]
Self-hosted or live as is?

**Comment by stephenjude** [comment]
Live

**Comment by stephenjude** [comment]
@Cannonb4ll any plans of fixing this?

**Comment by Cannonb4ll** [comment]
Yes.
