### ISSUE TITLE
[Idea] Grouping of similar exceptions

### ISSUE THREAD

**Issue by Wulfheart** [LaraBug/larabug-app#85]
The last idea for today. 😉
What about grouping exceptions which are the same? E.g. if an exception has the same stack trace and text then it is most probably the same exception with a slightly different context. 
I could add a occurence selector to the site for example left to the environment context:
![image](https://user-images.githubusercontent.com/25671390/173039202-5af83e40-2ca0-48ac-aa3a-2a37570d0af1.png)

**Comment by SebastiaanKloos** [comment]
@Wulfheart Yeah there is a branch for a feature I'm working on. We are going to test that very soon :) We are going to group the exceptions by issues. It's also able to sync with a GitHub repo for issues.

**Comment by Wulfheart** [comment]
Ah. Ok. Are you going to change many things?

**Comment by SebastiaanKloos** [comment]
I'm going to close this issue because we are already actively working on such a feature. You can still use master/main for other PR's
