### ISSUE TITLE
Missing Blade file

### ISSUE THREAD

**Issue by imanghafoori1** [LaraBug/larabug-app#92]
Where are the blade files?

![image](https://user-images.githubusercontent.com/6961695/175945658-badc61b9-9ac9-4443-8d41-b42f906e873a.png)

The complete report by the laravel-microscope is: [report.txt](https://github.com/LaraBug/larabug-app/files/8992126/report.txt)

**Comment by Cannonb4ll** [comment]
Probably not used anymore because of legacy code, a lot has changed and there's probably some unused views left.

Feel free to send in a PR with the adjustments.

**Comment by imanghafoori1** [comment]
Ok, I will remove the blade files which refer to missing blade files, so that the `check:view` finds no errors
